// nfl-hub server module — the op router the node executes.
//
// ⚠️ MUST BE BUNDLED BEFORE COMPILING. extism-js does not resolve imports — see
// build.sh. The browser half of this plugin needs no such step, which is a real
// difference between the two halves.
//
// ⚠️ NOT `export function run` — bundled to CJS, extism-js looks for
// `module.exports.run`. With `export` esbuild treats this as ESM, silently drops
// the assignment at the bottom, and emits a wasm with no entry point at all. It
// BUILDS CLEANLY either way; only running it shows the difference.

import { log, input, output, caller } from "./sdk/server-sdk.js";
import { principal } from "./auth.js";
import { storage } from "./sdk/server-sdk.js";
import {
  createLeague, listLeagues, getLeague, joinLeague, updateSettings,
  setLineup, getLineup, setAutoSubs, getAutoSubs, setTradeBlock, getTradeBlock,
  addFreeAgent, dropFreeAgent, movePlayer,
  generateSchedule, getSchedule,
} from "./ops-league.js";
import {
  createLeagueDraft, startLeagueDraft, getDraft, makeDraftPick,
  setDraftQueue, setDraftPaused, finalizeDraft,
} from "./ops-draft.js";
import {
  submitClaim, cancelClaim, listClaims, runWaivers,
  proposeLeagueTrade, respondToTrade, commissionerTrade, listTrades, settleTrades,
} from "./ops-transactions.js";
import {
  refreshPositions, scoreWeekForLeague, getScores, setCurrentWeek,
  runScoring, positionsAreStale, getStandings, advanceWeekIfDue, nflState,
  backfillOneWeek,
} from "./ops-scoring.js";
import { startPlayoffs, getPlayoffs, resolveBracketsFor } from "./ops-playoffs.js";
import {
  requestCoOwnership, respondToCoOwnerRequest, removeCoOwner,
} from "./ops-coowners.js";
// ⚠️ GENERATED BY build.sh from manifest.json. Never a constant here again — as
// one it lagged every forgotten bump, and `ping` then reported a build that was
// not running.
import { MODULE_VERSION } from "./version.js";

// A flat table rather than a switch, so the op list is greppable and each op
// stays independently testable.
const OPS = {
  // Diagnostics — kept from 0.1.0 because they are how the publish path is
  // verified against a live node without any league existing.
  ping: ({ payload }) => ({ pong: true, module_version: MODULE_VERSION, echo: payload ?? null }),
  "diag:storage": () => {
    const key = "diag:roundtrip";
    const wrote = { at: MODULE_VERSION, n: (storage.get(key)?.n ?? 0) + 1 };
    storage.set(key, wrote);
    return { wrote, read: storage.get(key) };
  },
  "diag:swap": () => {
    const before = storage.getVersioned("diag:counter");
    const after = storage.swap("diag:counter", (c) => ({ n: (c?.n ?? 0) + 1 }), { fallback: { n: 0 } });
    return { before_version: before.version, after, version: storage.getVersioned("diag:counter").version };
  },
  "diag:whoami": ({ p }) => ({ userId: p.userId, scheduled: p.scheduled }),

  // League
  "league:create": createLeague,
  "league:list": listLeagues,
  "league:get": getLeague,
  "league:join": joinLeague,
  "league:settings": updateSettings,
  "schedule:generate": generateSchedule,
  "schedule:get": getSchedule,

  // Co-ownership — a handshake, so both ids come from a verified session.
  // See ops-coowners.js for why an owner cannot simply name somebody.
  "team:coowner:request": requestCoOwnership,
  "team:coowner:respond": respondToCoOwnerRequest,
  "team:coowner:remove": removeCoOwner,

  // Rosters and lineups
  "lineup:set": setLineup,
  "lineup:get": getLineup,
  "autosub:set": setAutoSubs,
  "autosub:get": getAutoSubs,
  "tradeblock:set": setTradeBlock,
  "tradeblock:get": getTradeBlock,
  "roster:add": addFreeAgent,
  "roster:drop": dropFreeAgent,
  "roster:move": movePlayer,

  // Draft
  "draft:create": createLeagueDraft,
  "draft:start": startLeagueDraft,
  "draft:get": getDraft,
  "draft:pick": makeDraftPick,
  "draft:queue": setDraftQueue,
  "draft:pause": setDraftPaused,
  "draft:finalize": finalizeDraft,

  // Waivers
  "waiver:submit": submitClaim,
  "waiver:cancel": cancelClaim,
  "waiver:list": listClaims,

  // Trades
  "trade:propose": proposeLeagueTrade,
  "trade:respond": respondToTrade,
  "trade:commissioner": commissionerTrade,
  "trade:list": listTrades,

  // Scoring
  "scores:get": getScores,
  "standings:get": getStandings,
  "playoffs:start": startPlayoffs,
  "playoffs:get": getPlayoffs,
  "league:week": setCurrentWeek,
  "positions:refresh": refreshPositions,

  // Scheduled only — these refuse a user-triggered run themselves, in auth.js.
  "tick:waivers": runWaivers,
  "tick:trades": settleTrades,
  "tick:scores": scoreWeekForLeague,
};

/**
 * The scheduled tick.
 *
 * ⚠️ EVERY LEAGUE, EVERY TICK, WITHIN 5 SECONDS. A league whose work does not
 * fit must be chunked across ticks rather than allowed to run long — the runtime
 * kills the invocation at the deadline and whatever had not been written is
 * simply lost. Each league's work is wrapped so one bad league cannot stop the
 * others from being processed.
 */
function runScheduledTick(p) {
  const leagues = storage.get("fl:index") ?? [];
  const results = [];

  // Positions first: everything that validates or scores a lineup depends on
  // them, and a week-old map is fine — positions change on signings, not hourly.
  // Refreshed before the leagues so the very first tick of a new install has
  // them, rather than skipping a week.
  if (leagues.length > 0 && positionsAreStale()) {
    try {
      results.push({ task: "positions", result: refreshPositions({ p, payload: {} }) });
    } catch (err) {
      log(`tick positions failed: ${err.message}`);
      results.push({ task: "positions", error: String(err.message ?? err) });
    }
  }
  // ⚠️ ONCE PER TICK, not once per league. It is the same answer for every
  // league on the install, and the daily fetch allowance is finite.
  let state = null;
  if (leagues.length > 0) {
    try {
      state = nflState();
    } catch (err) {
      log(`tick: could not read the NFL state: ${err.message}`);
    }
  }

  for (const leagueId of leagues) {
    // Advance BEFORE reading the week, so a league that just rolled over scores
    // its new week on this tick rather than the next one.
    if (state) {
      try {
        const adv = advanceWeekIfDue(leagueId, state);
        if (adv.advanced) results.push({ leagueId, task: "week", result: adv });
      } catch (err) {
        log(`tick week advance failed for ${leagueId}: ${err.message}`);
      }
    }

    const meta = storage.get(`fl:${leagueId}:meta`);
    if (!meta) continue;
    const season = meta.season;
    const week = meta.currentWeek ?? null;

    for (const [name, fn, payload] of [
      ["trades", settleTrades, { leagueId }],
      ["waivers", runWaivers, { leagueId, season, week }],
      // ⚠️ Scoring is called through runScoring, not the op, because the op
      // requires a scheduled principal and re-checking it here would be a second
      // definition of the same rule.
      ["scores", () => runScoring(leagueId, season, week), null],
      // After scoring, not before: a round is decided by the week that was just
      // scored, so advancing first would always be one tick behind.
      ["playoffs", () => resolveBracketsFor(leagueId, season), null],
    ]) {
      if ((name === "waivers" || name === "scores") && !week) continue;
      try {
        results.push({ leagueId, task: name, result: fn({ p, payload }) });
      } catch (err) {
        // One league's failure must not stop the tick. Logged so it is visible
        // in the node log rather than swallowed into a success.
        log(`tick ${name} failed for ${leagueId}: ${err.message}`);
        results.push({ leagueId, task: name, error: String(err.message ?? err) });
      }
    }
  }
  // ⚠️ ONE BACKFILL PER TICK ACROSS THE WHOLE INSTALL, not per league. Each
  // repaired week is a 570 KB fetch and the entire tick has 5 seconds; doing it
  // per league would blow the deadline and lose the writes already made.
  // Repairs are rare — this only fires after an outage — so slow is fine.
  for (const leagueId of leagues) {
    let repaired = null;
    try {
      repaired = backfillOneWeek(leagueId);
    } catch (err) {
      log(`tick backfill failed for ${leagueId}: ${err.message}`);
    }
    if (repaired) {
      results.push({ leagueId, task: "backfill", result: repaired });
      break; // one per tick, whichever league needed it first
    }
  }

  return { tick: true, leagues: leagues.length, results };
}

function run() {
  const req = input() ?? {};
  const p = principal(caller);

  // A scheduled run arrives with {"trigger":"schedule"} and no op.
  if (p.scheduled && !req.op) {
    try {
      output({ ok: true, data: runScheduledTick(p) });
    } catch (err) {
      log(`scheduled tick failed: ${err.message}`);
      output({ ok: false, error: String(err.message ?? err) });
    }
    return 0;
  }

  const handler = OPS[req.op];
  if (!handler) {
    // Named ops only. An unknown op is a caller bug and is never guessed at.
    output({ ok: false, error: `unknown op: ${req.op ?? "(none)"}`, ops: Object.keys(OPS) });
    return 0;
  }

  try {
    output({ ok: true, data: handler({ p, payload: req.payload }) });
  } catch (err) {
    // A refusal — an illegal move, a permission failure, a host limit — is
    // reported as data rather than trapping, so the caller gets a usable message
    // instead of an opaque "trap" outcome.
    log(`${req.op} failed: ${err.message}`);
    output({ ok: false, error: String(err.message ?? err) });
  }
  return 0;
}

module.exports = { run };
