/**
 * Generate the vendored copies of the shared modules that live at the plugins root.
 *
 * WHY THIS EXISTS. A mirror may only copy files from **under a plugin's own directory**
 * (`internal/pluginmirror.RelPath` in dissent-core rejects anything else — reaching above
 * your directory is how one plugin would take another's files). So a plugin that does
 * `import { scrapeRLStats } from '../rl-scraper.js'` cannot be mirrored at all: the node
 * has nothing to enumerate, and the import keeps resolving to whoever published it. That
 * is what held `dnd-master`, `dnd-player`, `rl-hub`, `rl-sidebar` and `ufc-hub` back from
 * mirroring on 2026-08-15 while the other twelve went through.
 *
 * WHY GENERATED RATHER THAN COPIED BY HAND. Vendoring means N copies, and N copies drift.
 * `polymarket.js` says so in its own header, and it is right for a reason that is not
 * stylistic — it is the single choke point (`placeBet`) between a config setting and a
 * real-money order, and the whole argument for it collapses if a second copy can quietly
 * answer differently. So the module still lives in exactly one place and the copies are
 * *output*. `--check` fails the build when a copy stops matching, which is the only thing
 * that makes "one source of truth" true rather than aspirational.
 *
 * ⚠️ THE COPIES ARE BUILD OUTPUT. Never hand-edit one — edit the root module and re-run
 * this. Each generated file carries a header saying so.
 *
 * ⚠️ `plugin-sdk.js` IS NOT VENDORED and must not be. The node serves it from its own
 * origin at `/plugins/plugin-sdk.js` (see `plugin_sdk.go`), so `../plugin-sdk.js` resolves
 * on a mirroring node without being copied anywhere. It is the one shared module with a
 * real home. The import is rewritten per target *depth*, because a copy two directories
 * down needs `../../`.
 *
 * Usage:
 *   node scripts/vendor-shared.mjs            # write the copies
 *   node scripts/vendor-shared.mjs --check    # write nothing; exit 1 if any copy is stale
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const PLUGINS_DIR = new URL("../plugins/", import.meta.url).pathname;

/**
 * source: the module at the plugins root, which stays the single source of truth.
 * targets: where a copy is generated, relative to plugins/.
 *
 * A target's path determines the SDK import depth, so nesting is handled automatically —
 * `ufc-hub/core/…` gets `../../plugin-sdk.js` and `rl-hub/…` gets `../plugin-sdk.js`.
 *
 * ⚠️ `ufc-hub` already has a DIFFERENT `core/polymarket.js` (implied win probability for a
 * card). The trading module is vendored under a distinct name so the two never collide.
 */
const VENDORED = [
  {
    source: "rl-scraper.js",
    targets: ["rl-hub/rl-scraper.js", "rl-sidebar/rl-scraper.js"],
  },
  {
    source: "dnd-hub-shared-storage.js",
    targets: [
      "dnd-master/dnd-hub-shared-storage.js",
      "dnd-player/dnd-hub-shared-storage.js",
    ],
  },
  {
    source: "polymarket.js",
    targets: ["ufc-hub/core/polymarket-trade.js"],
  },
  // Three-way campaign merge used by every D&D save path (hub and both companions).
  {
    source: "dnd-campaign-merge.js",
    targets: [
      "dnd-hub/dnd-campaign-merge.js",
      "dnd-master/dnd-campaign-merge.js",
      "dnd-player/dnd-campaign-merge.js",
    ],
  },
  // LanternKeep content packs (sample adventure now, PDF import later).
  {
    source: "lk-content-pack.js",
    targets: ["dnd-hub/lk-content-pack.js", "dnd-master/lk-content-pack.js", "dnd-player/lk-content-pack.js"],
  },
  // LanternKeep Table rules — the presets and what each switch means.
  {
    source: "lk-table-rules.js",
    targets: ["dnd-hub/lk-table-rules.js", "dnd-master/lk-table-rules.js", "dnd-player/lk-table-rules.js"],
  },
  // Uploads — one helper that shows the node's "where to get storage" message.
  {
    source: "lk-upload.js",
    targets: ["dnd-hub/lk-upload.js", "dnd-master/lk-upload.js", "dnd-player/lk-upload.js"],
  },
  // Party at a glance — the DM's rows and the players' strip (the Hub draws neither).
  {
    source: "lk-party.js",
    targets: ["dnd-master/lk-party.js", "dnd-player/lk-party.js"],
  },
  // How the three LanternKeep plugins reach each other (a plain realtimePublish reaches only itself).
  {
    source: "lk-bus.js",
    targets: ["dnd-hub/lk-bus.js", "dnd-master/lk-bus.js", "dnd-player/lk-bus.js"],
  },
  // LanternKeep's 5e rules — one tested module, so every D&D plugin computes the same numbers.
  {
    source: "lk-rules5e.js",
    targets: ["dnd-hub/lk-rules5e.js", "dnd-master/lk-rules5e.js", "dnd-player/lk-rules5e.js"],
  },
  // Which campaign a D&D sidebar shows — one answer for dnd-player and dnd-master.
  {
    source: "dnd-campaign-pick.js",
    targets: ["dnd-master/dnd-campaign-pick.js", "dnd-player/dnd-campaign-pick.js"],
  },
  // LanternKeep icons (Lucide, ISC), generated by scripts/build-lk-icons.mjs.
  { source: "lk-icons.js", targets: ["dnd-hub/lk-icons.js", "dnd-master/lk-icons.js", "dnd-player/lk-icons.js"] },
  // LanternKeep look: one theme and its font, in all three plugins (raw / binary copies).
  ...["dnd-hub", "dnd-master", "dnd-player"].flatMap((id) => [
    { source: "lanternkeep-theme.css", raw: true, targets: [`${id}/lanternkeep-theme.css`] },
    { source: "lanternkeep-fonts/OFL.txt", raw: true, targets: [`${id}/lanternkeep-fonts/OFL.txt`] },
    ...["Cinzel-latin.woff2", "Cinzel-latin-ext.woff2"].map((f) => ({
      source: `lanternkeep-fonts/${f}`, binary: true, targets: [`${id}/lanternkeep-fonts/${f}`],
    })),
  ]),
  // The realtime event vocabulary all three D&D plugins speak. dnd-hub included: it is a
  // copy there too, so no plugin owns the vocabulary the others depend on.
  {
    source: "dnd-hub-event-types.js",
    targets: [
      "dnd-hub/dnd-hub-event-types.js",
      "dnd-master/dnd-hub-event-types.js",
      "dnd-player/dnd-hub-event-types.js",
    ],
  },
  // 🔴 SRD data, copied byte-for-byte (`raw`: no banner, JSON has no comments).
  // dnd-master and dnd-player used to fetch it from '../dnd-hub/dnd-srd/'. Since
  // 2026-10-02 every mirrored plugin has its OWN origin (<label>.<PLUGIN_HOST_DOMAIN>),
  // and the node refuses to serve one plugin's files from another's origin — so that
  // fetch is a CORS failure and the sidebar never loads. Each plugin carries what it reads.
  ...["monsters.json"].map((f) => ({
    source: `dnd-hub/dnd-srd/${f}`, raw: true, targets: [`dnd-master/dnd-srd/${f}`],
  })),
  ...["classes.json", "feats.json", "spells.json"].map((f) => ({
    source: `dnd-hub/dnd-srd/${f}`, raw: true, targets: [`dnd-player/dnd-srd/${f}`],
  })),
];

/** How many directories below plugins/ a target sits — i.e. how many `../` reach the root. */
function depthOf(target) {
  return target.split("/").length - 1;
}

function banner(source, target) {
  const up = "../".repeat(depthOf(target));
  return [
    `// ⚠️ GENERATED FILE — DO NOT EDIT.`,
    `//`,
    `// Vendored from plugins/${source} by scripts/vendor-shared.mjs.`,
    `// Edit that file and re-run the script; \`--check\` fails the deploy if this copy drifts.`,
    `//`,
    `// It is a copy because a mirror may only serve files from under this plugin's own`,
    `// directory, so importing '${up}${source}' directly would make the plugin unmirrorable.`,
    ``,
    ``,
  ].join("\n");
}

/** Rewrite the source's own SDK import for where the copy will live. */
function render(source, target) {
  const raw = readFileSync(join(PLUGINS_DIR, source), "utf8");
  const up = "../".repeat(depthOf(target));

  let seen = 0;
  const body = raw.replace(
    /(['"])\.\/plugin-sdk\.js\1/g,
    (_m, q) => {
      seen++;
      return `${q}${up}plugin-sdk.js${q}`;
    },
  );

  // A source that stopped importing the SDK is fine; one whose import shape changed is not.
  // Silently emitting a copy with an unresolvable './plugin-sdk.js' would present as the
  // plugin's features simply being absent, which is exactly the failure mode this whole
  // area keeps producing.
  if (raw.includes("plugin-sdk.js") && seen === 0) {
    throw new Error(
      `plugins/${source} references plugin-sdk.js but not as './plugin-sdk.js' — ` +
        `the rewrite would leave an unresolvable specifier in ${target}. Fix the source or this script.`,
    );
  }
  return banner(source, target) + body;
}

const sha = (s) => createHash("sha256").update(s).digest("hex").slice(0, 12);

const check = process.argv.includes("--check");
let stale = 0;
let wrote = 0;

for (const { source, targets, raw, binary } of VENDORED) {
  if (!existsSync(join(PLUGINS_DIR, source))) {
    console.error(`✗ missing source: plugins/${source}`);
    process.exit(1);
  }
  for (const target of targets) {
    // binary: byte-for-byte (fonts, images) — never decoded as text.
    const want = binary ? readFileSync(join(PLUGINS_DIR, source))
      : raw ? readFileSync(join(PLUGINS_DIR, source), "utf8") : render(source, target);
    const path = join(PLUGINS_DIR, target);
    const have = existsSync(path) ? readFileSync(path, binary ? undefined : "utf8") : null;

    if (binary ? (have && Buffer.compare(have, want) === 0) : have === want) {
      console.log(`  ok    ${target}  (${sha(want)})`);
      continue;
    }
    if (check) {
      stale++;
      console.error(
        `✗ STALE  ${target}\n         regenerate with: node scripts/vendor-shared.mjs`,
      );
      continue;
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, want);
    wrote++;
    console.log(`  write ${target}  ← plugins/${source}  (${sha(want)})`);
  }
}

if (check && stale > 0) {
  console.error(
    `\n${stale} vendored cop${stale === 1 ? "y is" : "ies are"} out of date with the root module.`,
  );
  process.exit(1);
}
console.log(
  check
    ? `\nAll vendored copies match their source.`
    : `\n${wrote} written, ${VENDORED.reduce((n, v) => n + v.targets.length, 0) - wrote} already current.`,
);
