// core/draft-ranking.js — the client's copy of the draft ranking.
//
// One loader shared by the live draft and the mock, so the 22 KB asset is
// fetched once per session rather than once per board.
//
// ⚠️ THE RANKING IS THE MARKET'S ORDER FOR THE SEASON BEING DRAFTED — Sleeper
// ADP, with season projections behind it for players the market has not priced.
// It is generated by scripts/build-draft-ranking.mjs and REGENERATED EACH YEAR;
// a stale asset is the failure mode, not a wrong formula.
//
// ⚠️ IT WAS BACKWARD-LOOKING UNTIL 2026-08-31 and that was the reported bug. It
// ranked last season's ACTUAL points, so it could not contain a rookie at all
// and ranked everyone else on a depth chart that had since changed. Correct for
// the season that had finished; not the season anyone was drafting.

let ranking = null;
let loading = null;

/** Inject a ranking directly. For tests, and for a view that already has one. */
export function setRanking(value) {
  ranking = value;
  loading = null;
}

/** The loaded ranking, or null if it has not loaded yet. */
export function getRanking() {
  return ranking;
}

/**
 * Load the ranking once. Concurrent callers share the same request.
 *
 * ⚠️ THROWS ON FAILURE, unlike the player index. A missing index degrades names
 * to ids and the screen still works; a missing ranking leaves a draft board with
 * no players in it, and pretending that is an empty pool would tell a manager
 * that everybody is already drafted.
 */
export async function loadRanking() {
  if (ranking) return ranking;
  if (loading) return loading;
  loading = (async () => {
    try {
      const res = await fetch(new URL('../assets/draft-ranking.json', import.meta.url));
      if (!res.ok) throw new Error(`draft ranking ${res.status}`);
      ranking = await res.json();
      return ranking;
    } finally {
      loading = null;
    }
  })();
  return loading;
}

/**
 * The ordered id list for a scoring type.
 *
 * Falls back to PPR for an unrecognised type rather than returning nothing — a
 * league with an unusual scoring name should still get a board.
 */
export function rankingFor(scoring = 'ppr') {
  const key = String(scoring ?? 'ppr').toLowerCase();
  const list = ranking?.[key];
  if (Array.isArray(list) && list.length) return list;
  return Array.isArray(ranking?.ppr) ? ranking.ppr : [];
}

/**
 * Which ranking a league's scoring settings correspond to.
 *
 * ⚠️ `settings.scoring` IS A WEIGHT MAP, NOT A NAME. It is the full
 * `{ rec: 1, rec_yd: 0.1, … }` object, so passing it straight to `rankingFor`
 * stringifies it to "[object object]", matches no key, and silently falls back
 * to PPR — a half-PPR or standard league would quietly get the PPR board and
 * nothing would say so. The fallback is right for an unknown name and wrong as
 * a way of handling a known object.
 *
 * The reception weight is the only thing that separates the three presets
 * (`HALF_PPR_SCORING` and `STANDARD_SCORING` are `{...PPR_SCORING, rec}`), so it
 * is what decides. A string passes through, which is what the mock draft sends.
 */
export function scoringKeyFor(scoring) {
  if (typeof scoring === 'string') return scoring.toLowerCase();
  const rec = scoring?.rec;
  if (typeof rec !== 'number') return 'ppr';
  if (rec >= 0.75) return 'ppr';
  if (rec >= 0.25) return 'half';
  return 'std';
}

/**
 * A player's value over replacement, for a league's scoring.
 *
 * ⚠️ PRESEASON PROJECTION, and callers must say so on screen. It is what the
 * draft board was built from — useful for weighing a trade precisely because
 * both sides were drafted against it — but it knows nothing about what has
 * happened since. Returns null when the player is outside the ranking's depth,
 * which is normal and must render as "—" rather than as zero.
 */
export function valueOf(playerId, scoring = 'ppr') {
  const v = ranking?.[`${scoringKeyFor(scoring)}_v`]?.[String(playerId)];
  return typeof v === 'number' ? v : null;
}
